return {
	{ import = "plugins.fzf" },
	{ import = "plugins.oil" },
	{ import = "plugins.colorscheme" },
	{ import = "plugins.treesitter" },
	{ import = "plugins.blink" },
	{ import = "plugins.lsp" },
	{ import = "plugins.noice" },
	{ import = "plugins.statusline" },
	{ import = "plugins.snacks" },
	{ import = "plugins.bufferline" },
	{ import = "plugins.dashboard" },
	{ import = "plugins.tabout" },
	{ import = "plugins.todo-comments" },
	{ import = "plugins.nvim-highlight-colors" },
	{ import = "plugins.mini" },
	{ import = "plugins.flash" },
	{ import = "plugins.conform" },
	{ import = "plugins.trouble" },
}
