return {
  {
    "catgoose/nvim-colorizer.lua",
    cmd = { "ColorizerAttachToBuffer", "ColorizerDetachFromBuffer", "ColorizerReloadAllBuffers", "ColorizerToggle" },
    event = "VeryLazy",
    opts = {
      filetypes = {
        "css",
        "scss",
        "sass",
        "less",
        "html",
        "htmldjango",
        "javascript",
        "javascriptreact",
        "typescript",
        "typescriptreact",
        "vue",
        "svelte",
        "lua",
      },
      user_default_options = {
        RGB = true,
        RRGGBB = true,
        RRGGBBAA = true,
        AARRGGBB = true,
        names = false,
        rgb_fn = true,
        hsl_fn = true,
        css = true,
        css_fn = true,
        tailwind = true,
        tailwind_opts = {
          update_names = false,
        },
        mode = "virtualtext",
        virtualtext = "■",
        virtualtext_inline = "after",
        virtualtext_mode = "foreground",
        always_update = false,
      },
    },
  },
}
