---@type Base46Table
local M = {}

local call_blue = "#66A6FF"
local type_teal = "#2FBAA3"

M.base_30 = {
  white = "#BCBEC4",
  black = "#1F1F24",
  darker_black = "#1B1B20",
  black2 = "#232329",
  one_bg = "#2A2B31",
  one_bg2 = "#313239",
  one_bg3 = "#3A3B43",
  grey = "#5F636A",
  grey_fg = "#6B7078",
  grey_fg2 = "#7A7E85",
  light_grey = "#9DA0A8",
  red = "#F75464",
  baby_pink = "#D17FAF",
  pink = "#C77DBB",
  line = "#2C2D33",
  green = "#6AAB73",
  vibrant_green = "#7BC487",
  nord_blue = call_blue,
  blue = call_blue,
  seablue = "#2AACB8",
  yellow = "#D5B778",
  sun = "#E4C98A",
  purple = type_teal,
  dark_purple = "#259987",
  teal = type_teal,
  orange = "#CF8E6D",
  cyan = "#2AACB8",
  statusline_bg = "#25262D",
  lightbg = "#2A2B31",
  pmenu_bg = call_blue,
  folder_bg = call_blue,
}

M.base_16 = {
  base00 = "#1F1F24",
  base01 = "#232329",
  base02 = "#25262D",
  base03 = "#5F636A",
  base04 = "#7A7E85",
  base05 = "#BCBEC4",
  base06 = "#D5D7DE",
  base07 = "#FFFFFF",
  base08 = "#F75464",
  base09 = "#CF8E6D",
  base0A = "#D5B778",
  base0B = "#6AAB73",
  base0C = "#2AACB8",
  base0D = call_blue,
  base0E = type_teal,
  base0F = "#C77DBB",
}

M.polish_hl = {
  defaults = {
    HTML_InjectedLanguageFragment = { bg = "NONE" },
  },

  treesitter = {
    ["@comment"] = { fg = "#7A7E85" },
    ["@comment.documentation"] = { fg = "#5F826B", italic = true },
    ["@keyword"] = { fg = "#CF8E6D" },
    ["@keyword.import"] = { fg = "#CF8E6D" },
    ["@keyword.return"] = { fg = "#CF8E6D" },
    ["@keyword.exception"] = { fg = "#F75464" },
    ["@keyword.operator"] = { fg = "#BCBEC4" },
    ["@keyword.directive"] = { fg = "#CF8E6D" },
    ["@string"] = { fg = "#6AAB73" },
    ["@string.regexp"] = { fg = "#D16969" },
    ["@string.escape"] = { fg = "#D5B778" },
    ["@character"] = { fg = "#6AAB73" },
    ["@character.special"] = { fg = "#CF8E6D" },
    ["@number"] = { fg = "#2AACB8" },
    ["@boolean"] = { fg = "#CF8E6D" },
    ["@float"] = { fg = "#2AACB8" },
    ["@constant"] = { fg = "#C77DBB", italic = true },
    ["@constant.builtin"] = { fg = "#CF8E6D" },
    ["@constant.macro"] = { fg = "#B3AE60" },
    ["@function"] = { fg = call_blue },
    ["@function.call"] = { fg = call_blue },
    ["@function.builtin"] = { fg = call_blue },
    ["@function.macro"] = { fg = "#B3AE60" },
    ["@function.method"] = { fg = call_blue },
    ["@function.method.call"] = { fg = call_blue },
    ["@method"] = { fg = call_blue },
    ["@method.call"] = { fg = call_blue },
    ["@constructor"] = { fg = call_blue },
    ["@function.call.python"] = { fg = call_blue },
    ["@function.builtin.python"] = { fg = call_blue },
    ["@function.method.call.python"] = { fg = call_blue },
    ["@type"] = { fg = type_teal },
    ["@type.builtin"] = { fg = type_teal },
    ["@type.definition"] = { fg = type_teal },
    ["@type.parameter"] = { fg = "#16BAAC" },
    ["@namespace"] = { fg = "#B3AE60" },
    ["@module"] = { fg = "#B3AE60" },
    ["@variable"] = { fg = "#BCBEC4" },
    ["@variable.builtin"] = { fg = "#C77DBB" },
    ["@variable.parameter"] = { fg = "#BCBEC4" },
    ["@variable.member"] = { fg = "#C77DBB" },
    ["@property"] = { fg = "#C77DBB" },
    ["@attribute"] = { fg = "#B3AE60" },
    ["@label"] = { fg = "#BCBEC4" },
    ["@operator"] = { fg = "#BCBEC4" },
    ["@punctuation"] = { fg = "#BCBEC4" },
    ["@punctuation.bracket"] = { fg = "#BCBEC4" },
    ["@punctuation.delimiter"] = { fg = "#BCBEC4" },
    ["@punctuation.special"] = { fg = "#CF8E6D" },
    ["@tag"] = { fg = "#BCBEC4" },
    ["@tag.attribute"] = { fg = "#C77DBB" },
    ["@tag.delimiter"] = { fg = "#9DA0A8" },
    ["@text.literal"] = { fg = "#6AAB73" },
    ["@text.uri"] = { fg = "#548AF7", underline = true },
    ["@markup.heading"] = { fg = "#CF8E6D", bold = true },
    ["@markup.link"] = { fg = "#548AF7", underline = true },
    ["@markup.raw"] = { fg = "#6AAB73" },
    ["@markup.list"] = { fg = "#CF8E6D" },
    ["@diff.plus"] = { fg = "#549159" },
    ["@diff.minus"] = { fg = "#868A91" },
    ["@diff.delta"] = { fg = "#375FAD" },
  },
}

M.type = "dark"

M = require("base46").override_theme(M, "JB Dark")

return M
