local M = {}

local call_blue = "#66A6FF"
local type_teal = "#2FBAA3"

local dark = {
  ["@comment"] = { fg = "#7A7E85" },
  ["@comment.documentation"] = { fg = "#5F826B", italic = true },
  ["@keyword"] = { fg = "#CF8E6D" },
  ["@keyword.import"] = { fg = "#CF8E6D" },
  ["@keyword.return"] = { fg = "#CF8E6D" },
  ["@keyword.exception"] = { fg = "#F75464" },
  ["@keyword.operator"] = { fg = "#BCBEC4" },
  ["@keyword.directive"] = { fg = "#CF8E6D" },
  ["@string"] = { fg = "#6AAB73" },
  ["@string.regexp"] = { fg = "#D16969" },
  ["@string.escape"] = { fg = "#D5B778" },
  ["@character"] = { fg = "#6AAB73" },
  ["@character.special"] = { fg = "#CF8E6D" },
  ["@number"] = { fg = "#2AACB8" },
  ["@boolean"] = { fg = "#CF8E6D" },
  ["@float"] = { fg = "#2AACB8" },
  ["@constant"] = { fg = "#C77DBB", italic = true },
  ["@constant.builtin"] = { fg = "#CF8E6D" },
  ["@constant.macro"] = { fg = "#B3AE60" },
  ["@function"] = { fg = call_blue },
  ["@function.call"] = { fg = call_blue },
  ["@function.builtin"] = { fg = call_blue },
  ["@function.macro"] = { fg = "#B3AE60" },
  ["@function.method"] = { fg = call_blue },
  ["@function.method.call"] = { fg = call_blue },
  ["@method"] = { fg = call_blue },
  ["@method.call"] = { fg = call_blue },
  ["@constructor"] = { fg = call_blue },
  ["@function.call.python"] = { fg = call_blue },
  ["@function.builtin.python"] = { fg = call_blue },
  ["@function.method.call.python"] = { fg = call_blue },
  ["@type"] = { fg = type_teal },
  ["@type.builtin"] = { fg = type_teal },
  ["@type.definition"] = { fg = type_teal },
  ["@type.parameter"] = { fg = "#16BAAC" },
  ["@namespace"] = { fg = "#B3AE60" },
  ["@module"] = { fg = "#B3AE60" },
  ["@variable"] = { fg = "#BCBEC4" },
  ["@variable.builtin"] = { fg = "#C77DBB" },
  ["@variable.parameter"] = { fg = "#BCBEC4" },
  ["@variable.member"] = { fg = "#C77DBB" },
  ["@property"] = { fg = "#C77DBB" },
  ["@attribute"] = { fg = "#B3AE60" },
  ["@label"] = { fg = "#BCBEC4" },
  ["@operator"] = { fg = "#BCBEC4" },
  ["@punctuation"] = { fg = "#BCBEC4" },
  ["@punctuation.bracket"] = { fg = "#BCBEC4" },
  ["@punctuation.delimiter"] = { fg = "#BCBEC4" },
  ["@punctuation.special"] = { fg = "#CF8E6D" },
  ["@tag"] = { fg = "#BCBEC4" },
  ["@tag.attribute"] = { fg = "#C77DBB" },
  ["@tag.delimiter"] = { fg = "#9DA0A8" },
  ["@text.literal"] = { fg = "#6AAB73" },
  ["@text.uri"] = { fg = "#548AF7", underline = true },
  ["@markup.heading"] = { fg = "#CF8E6D", bold = true },
  ["@markup.link"] = { fg = "#548AF7", underline = true },
  ["@markup.raw"] = { fg = "#6AAB73" },
  ["@markup.list"] = { fg = "#CF8E6D" },
  ["@diff.plus"] = { fg = "#549159" },
  ["@diff.minus"] = { fg = "#868A91" },
  ["@diff.delta"] = { fg = "#375FAD" },
  ["HTML_InjectedLanguageFragment"] = { bg = "NONE" },
}

local light_call_blue = "#1750EB"
local light_type_teal = "#007E8A"

local light = {
  ["@comment"] = { fg = "#8C8C8C", italic = true },
  ["@comment.documentation"] = { fg = "#8C8C8C", italic = true },
  ["@keyword"] = { fg = "#0033B3", bold = true },
  ["@keyword.import"] = { fg = "#0033B3", bold = true },
  ["@keyword.return"] = { fg = "#0033B3", bold = true },
  ["@keyword.exception"] = { fg = "#B42318" },
  ["@keyword.operator"] = { fg = "#1F1F1F" },
  ["@keyword.directive"] = { fg = "#0033B3", bold = true },
  ["@string"] = { fg = "#067D17", bold = true },
  ["@string.regexp"] = { fg = "#B42318" },
  ["@string.escape"] = { fg = "#8B6914" },
  ["@character"] = { fg = "#067D17", bold = true },
  ["@character.special"] = { fg = "#0033B3" },
  ["@number"] = { fg = "#1750EB", bold = true },
  ["@boolean"] = { fg = "#0033B3", bold = true },
  ["@float"] = { fg = "#1750EB", bold = true },
  ["@constant"] = { fg = "#871094", italic = true },
  ["@constant.builtin"] = { fg = "#0033B3", bold = true },
  ["@constant.macro"] = { fg = "#9E880D" },
  ["@function"] = { fg = light_call_blue },
  ["@function.call"] = { fg = light_call_blue },
  ["@function.builtin"] = { fg = light_call_blue },
  ["@function.macro"] = { fg = "#9E880D" },
  ["@function.method"] = { fg = light_call_blue },
  ["@function.method.call"] = { fg = light_call_blue },
  ["@method"] = { fg = light_call_blue },
  ["@method.call"] = { fg = light_call_blue },
  ["@constructor"] = { fg = light_call_blue },
  ["@function.call.python"] = { fg = light_call_blue },
  ["@function.builtin.python"] = { fg = light_call_blue },
  ["@function.method.call.python"] = { fg = light_call_blue },
  ["@type"] = { fg = light_type_teal },
  ["@type.builtin"] = { fg = light_type_teal, bold = true },
  ["@type.definition"] = { fg = light_type_teal },
  ["@type.parameter"] = { fg = "#007E8A" },
  ["@namespace"] = { fg = "#9E880D" },
  ["@module"] = { fg = "#9E880D" },
  ["@variable"] = { fg = "#1F1F1F" },
  ["@variable.builtin"] = { fg = "#0033B3", bold = true },
  ["@variable.parameter"] = { fg = "#1F1F1F" },
  ["@variable.member"] = { fg = "#871094" },
  ["@property"] = { fg = "#871094" },
  ["@attribute"] = { fg = "#9E880D" },
  ["@label"] = { fg = "#1F1F1F" },
  ["@operator"] = { fg = "#1F1F1F" },
  ["@punctuation"] = { fg = "#1F1F1F" },
  ["@punctuation.bracket"] = { fg = "#1F1F1F" },
  ["@punctuation.delimiter"] = { fg = "#1F1F1F" },
  ["@punctuation.special"] = { fg = "#0033B3" },
  ["@tag"] = { fg = "#1F1F1F" },
  ["@tag.attribute"] = { fg = "#871094" },
  ["@tag.delimiter"] = { fg = "#5A5D6B" },
  ["@text.literal"] = { fg = "#067D17", bold = true },
  ["@text.uri"] = { fg = "#174AD4", underline = true },
  ["@markup.heading"] = { fg = "#0033B3", bold = true },
  ["@markup.link"] = { fg = "#174AD4", underline = true },
  ["@markup.raw"] = { fg = "#067D17", bold = true },
  ["@markup.list"] = { fg = "#0033B3" },
  ["@diff.plus"] = { fg = "#2E7D32" },
  ["@diff.minus"] = { fg = "#B42318" },
  ["@diff.delta"] = { fg = "#174AD4" },
  ["HTML_InjectedLanguageFragment"] = { bg = "NONE" },
}

function M.apply()
  if vim.g.colors_name ~= "jb" then
    return
  end
  local tbl = vim.o.background == "light" and light or dark
  for group, spec in pairs(tbl) do
    vim.api.nvim_set_hl(0, group, spec)
  end
end

return M
