---@type Base46Table
local M = {}

local p = {
  nc = "#16141f",
  base = "#191724",
  surface = "#1f1d2e",
  overlay = "#26233a",
  muted = "#6e6a86",
  subtle = "#908caa",
  text = "#e0def4",
  love = "#eb6f92",
  gold = "#f6c177",
  rose = "#ebbcba",
  pine = "#31748f",
  foam = "#9ccfd8",
  iris = "#c4a7e7",
  leaf = "#95b1ac",
  highlight_low = "#21202e",
  highlight_med = "#403d52",
  highlight_high = "#524f67",
}

M.base_30 = {
  white = p.text,
  black = p.base,
  darker_black = p.nc,
  black2 = p.surface,
  one_bg = p.highlight_low,
  one_bg2 = p.overlay,
  one_bg3 = p.highlight_med,
  grey = p.highlight_high,
  grey_fg = p.muted,
  grey_fg2 = p.subtle,
  light_grey = p.subtle,
  red = p.love,
  baby_pink = p.rose,
  pink = p.rose,
  line = p.overlay,
  green = p.foam,
  vibrant_green = p.leaf,
  nord_blue = p.pine,
  blue = p.iris,
  yellow = p.gold,
  sun = p.gold,
  purple = p.iris,
  dark_purple = p.muted,
  teal = p.foam,
  orange = p.rose,
  cyan = p.foam,
  statusline_bg = p.surface,
  lightbg = p.highlight_low,
  pmenu_bg = p.iris,
  folder_bg = p.foam,
}

M.base_16 = {
  base00 = p.base,
  base01 = p.surface,
  base02 = p.overlay,
  base03 = p.muted,
  base04 = p.subtle,
  base05 = p.text,
  base06 = p.rose,
  base07 = "#fffaf3",
  base08 = p.love,
  base09 = p.rose,
  base0A = p.gold,
  base0B = p.foam,
  base0C = p.rose,
  base0D = p.iris,
  base0E = p.pine,
  base0F = p.iris,
}

M.polish_hl = {
  defaults = {
    Normal = { fg = p.text, bg = p.base },
    NormalNC = { fg = p.text, bg = p.base },
    EndOfBuffer = { fg = p.base, bg = p.base },
    NormalFloat = { fg = p.text, bg = p.surface },
    FloatBorder = { fg = p.muted, bg = p.surface },
    WinSeparator = { fg = p.muted },
    SignColumn = { bg = p.base },
    CursorLine = { bg = p.highlight_low },
    Visual = { bg = p.highlight_med },
    Search = { fg = p.base, bg = p.gold },
    IncSearch = { fg = p.base, bg = p.rose },
    Pmenu = { fg = p.text, bg = p.surface },
    PmenuSel = { fg = p.base, bg = p.iris, bold = true },
    Comment = { fg = p.muted, italic = true },
  },

  syntax = {
    Boolean = { fg = p.rose },
    Character = { fg = p.foam },
    Conditional = { fg = p.pine, bold = true },
    Constant = { fg = p.rose },
    Define = { fg = p.pine },
    Delimiter = { fg = p.subtle },
    Exception = { fg = p.love },
    Float = { fg = p.rose },
    Function = { fg = p.iris },
    Identifier = { fg = p.text },
    Include = { fg = p.pine },
    Keyword = { fg = p.pine },
    Label = { fg = p.gold },
    Number = { fg = p.rose },
    Operator = { fg = p.subtle },
    PreProc = { fg = p.pine },
    Repeat = { fg = p.pine },
    Special = { fg = p.rose },
    Statement = { fg = p.pine },
    String = { fg = p.gold },
    Structure = { fg = p.foam },
    Type = { fg = p.foam },
  },

  treesitter = {
    ["@comment"] = { fg = p.muted, italic = true },
    ["@constant"] = { fg = p.rose },
    ["@constant.builtin"] = { fg = p.rose },
    ["@constructor"] = { fg = p.foam },
    ["@function"] = { fg = p.iris },
    ["@function.builtin"] = { fg = p.iris },
    ["@function.call"] = { fg = p.iris },
    ["@function.method"] = { fg = p.iris },
    ["@function.method.call"] = { fg = p.iris },
    ["@keyword"] = { fg = p.pine, bold = true },
    ["@keyword.import"] = { fg = p.pine },
    ["@keyword.return"] = { fg = p.pine, bold = true },
    ["@module"] = { fg = p.text },
    ["@number"] = { fg = p.rose },
    ["@operator"] = { fg = p.subtle },
    ["@punctuation.delimiter"] = { fg = p.subtle },
    ["@string"] = { fg = p.gold },
    ["@string.escape"] = { fg = p.rose },
    ["@tag"] = { fg = p.foam },
    ["@tag.attribute"] = { fg = p.iris },
    ["@tag.delimiter"] = { fg = p.subtle },
    ["@type"] = { fg = p.foam },
    ["@type.builtin"] = { fg = p.foam },
    ["@variable"] = { fg = p.text },
    ["@variable.builtin"] = { fg = p.love, italic = true },
    ["@variable.member"] = { fg = p.foam },
    ["@variable.parameter"] = { fg = p.rose, italic = true },
  },

  lsp = {
    DiagnosticError = { fg = p.love },
    DiagnosticWarn = { fg = p.gold },
    DiagnosticInfo = { fg = p.foam },
    DiagnosticHint = { fg = p.iris },
    DiagnosticOk = { fg = p.foam },
  },

  git = {
    DiffAdd = { fg = p.foam, bg = p.highlight_low },
    DiffChange = { fg = p.rose, bg = p.highlight_low },
    DiffDelete = { fg = p.love, bg = p.highlight_low },
    DiffText = { fg = p.rose, bg = p.highlight_med },
  },
}

M.type = "dark"

M = require("base46").override_theme(M, "Rose Pine")

return M
