theme = "onedark"

[editor]
line-number = "relative"
bufferline = "always"
indent-guides.enable = true
indent-guides.render = true
auto-pairs = true
color-modes = true
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["diagnostics"]
right = ["selections", "position", "file-encoding", "file-type"]


[editor.soft-wrap]
enable = true


[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
hidden = true

[keys.normal]
# "C-d" = ["half_page_down", "goto_window_center"]
# "C-u" = ["half_page_up", "goto_window_center"]
G = "goto_file_end"
"$" = "goto_line_end"
"0" = "goto_line_start"
"y" = "yank"
"J" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_down",
    "paste_before",
]
"K" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]

[keys.select]
G = "goto_file_end"
"$" = "goto_line_end"
"0" = "goto_line_start"
"y" = "yank"
"J" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_down",
    "paste_before",
]
"K" = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]

[keys.normal.space]
x = ":buffer-close"
