[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi", "pyc", "pyd", "pyw"]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "requirements.txt"]
comment-token = "#"
language-servers = ["pyright"]
indent = { tab-width = 4, unit = "    " }
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config]
python.analysis.typeCheckingMode = "off"
python.analysis.diagnosticMode = "workspace"
python.analysis.autoSearchPaths = true
python.analysis.useLibraryCodeForTypes = true
python.analysis.completeFunctionParens = true
